### ISSUE TITLE
Fix network constraint for eduroam

### ISSUE THREAD

**Issue by FHardow** [fub-agdb/tierklinik_app#1]
The network constraint is buggy and not upwards compatible to newer android versions.

**Comment by lhoff94** [comment]
Das Eduroam an der FU hat momentan keine IP Segmente je Institut/Fachbereich. Das ist wohl schon länger angedacht aber noch nicht umgesetzt. 

Der IP Bereich für das FU weite Eduroam ist 87.77.0.0 - 87.77.255.255
Wenn das im Backend geprüft wird, wäre das aus meiner Sicht schon ein Fortschritt gegenüber dem Status Quo weil es dann zumindest nur aus dem FU Eduroam funktioniert und nicht von anderen Unis aus.

**Comment by FHardow** [comment]
Der IP-Bereich ist aber für alle Nutzer der FU und statisch pro Nutzer. Ergo wirst du auch die gleiche IP bekommen wenn du dich an einer anderen Uni im Eduroam mit deinem Account einloggst.

**Comment by FHardow** [comment]
Wir haben heute mit dem Sysadmin bei den Vetis gesprochen. Er meinte dass wird nicht so einfach funktionieren und zu aufwendig. Wir werden den weg gehen dass sich jemand einen Wisch ausdenken wird auf dem so eine Art AGB draufsteht die eingehalten werden muss.
(z.B. nur in der Klinik nutzbar)

**Comment by lhoff94** [comment]
Also das man von einer wenn man sich an einer anderen Uni im Eduroam anmeldet eine IP aus dem Adressbereich der Heimatuni bekommt war zwar mal im ganzen Eduroamnetz so angedacht, wurde aber nie umgesetzt und ist mitterweile in der Spezifikation auch nichtmehr so vorgesehen.

Momentan ist das Backend aber ja sowieso nur von innerhalb des FU Netzes erreichbar. Falls sich das nicht ändern sollte gibt es eigentlich keinen Grund eine IP Bereichs Restriktion im Backend einzubauen da ja außerhalb des FU-Netzes eh keine Verbindung besteht. 

Was aus meiner Sicht aber noch sinnvoll wäre, ist einen Timeout bei Verbindungsaufbauten einzurichten und dann eine Fehlermeldung mit Hinweis auf mögliche Ursachen (nicht im FU Netz) in der App anzuzeigen.
