### ISSUE TITLE
Ungenutze Funktion zur Darstellung von Bildern

### ISSUE THREAD

**Issue by lhoff94** [fub-agdb/tierklinik_app#23]
Die Klassen:
`BilderBigviewActivity.java`, `BilderFragment.java` und `PhotoDialog.java` werden momentan nicht benutzt da in `AkteActivity.java` die entsprechenden Zeile auskommentiert.
```java
//disabled until new DICOM-system is there
//mSectionsPageAdapter.addFragment(new BilderFragment(), "Bildgebung");
```
@xconnect @FHardow 
Kommt die Funktion irgendwann zurück? Sollen wir die drei Momentan ungenutzen Klassen auch entsprechend refactored werden?

**Comment by FHardow** [comment]
Schiebt sie in einen `Deprecated` Ordner und baut es erstmal aus, aber nicht löschen 😄.
