### ISSUE TITLE
Kein Abstand zwischen Boxen in Flüssigkeitstherapie

### ISSUE THREAD

**Issue by lhoff94** [fub-agdb/tierklinik_app#4]
Abstand zwischen "Gewicht in kg" und "Berechnen" ist zu gering bzw. Nicht vorhanden.

![screenshot_20180808-205100](https://user-images.githubusercontent.com/17600225/43858168-a02a12c8-9b4d-11e8-8a23-16847f71e4e5.png)

**Comment by clgp2** [comment]
die KG-Box und die Gewicht-Box sind in den unterschiedlichen Ansichten des Medikamentenrechners nicht konsistent -> einheitliche Größe
![screenshot_1534334606](https://user-images.githubusercontent.com/15946710/44147442-7a74d738-a094-11e8-83ff-ab2459f7283d.png)
![screenshot_1534334499](https://user-images.githubusercontent.com/15946710/44147443-7a944c4e-a094-11e8-8f9b-6d65c5d7b5c7.png)
