### ISSUE TITLE
Design Refactor

### ISSUE THREAD

**Issue by groettrup** [fub-agdb/tierklinik_app#43]
* [x] SearchFragmentSuche
  - Bei Animalname wenn imeAction genutzt wird, auf nächstes Feld wechseln, statt suche

* [x] 3 Arten von Feldern
  - Titel
  - klickbar (farbig hinterlegt)
  - nicht klickbar

* [x] Suche und Favoriten wechseln den Platz
* [x] Rechts Maschinenname, unten Datum
* [x] Owner / Patient
  - Margins
  - Buttons (hinterlegen

* [x] ID hinter dem Namen
  - `Tier (ID)`
  - `Besitzer (ID)`
  - `Fallname (ID)`

* [x] Besitzer zentrieren
  - links / rechts
  - oben / unten
* [x] Besitzername fixieren
* [x] Telefon privat/mobil

**Comment by kathile97** [comment]
* [ ] Lupe bei suchen im patientenscreen

* [ ] Stern nicht zentriert
* [ ] Farbton der id gleich wie name darunter

## Tierscreen
* [ ] Tiername dick
* [ ] Id weg, nur Nummer
* [ ] Hundefoto einfügen
* [ ] Fälle einrücken / auf die Linie
* [ ] Pro Fall, id Name Weg und Datum drunter
* [ ] Besitzer, zweizeilig, "id" fällt raus

## Patientenansicht
* [ ] Id fällt raus
* [ ] Datum neu berechnen
* [ ] Telefon nummer (privat light grey)
* [ ] Tiere: light-grey raus - "id" raus

## Laborergebnisse
* [ ] Name der Maschine über des Datum
* [ ] Laborkarte drucken Farbe ändern
